DEBUG: True
SEED: 42

data:
  min_n_frames: 6
  max_n_frames: 20
  missing_face: 0.0
  missing_lhand: 0.0
  missing_rhand: 0.0
  missing_pose: 0.0
  filter_by_hand: right

model:
  num_gcn_scales: 13
  num_g3d_scales: 6

train:
  data_path: 'test'
  landmarks_to_include: 
    pose: ['POSE_UPPER']
    face:
    lhand:
    rhand: ['ALL']
  drop_z: True
  num_frames: 20
  num_epochs: 5
  batch_size: 32
  val_interval: 1
  save_interval: 1
  optimizer: 'torch.optim.Adam'
  lr_scheduler: 
    class: 'torch.optim.lr_scheduler.CosineAnnealingLR'
    params: 
      T_max: 3
      eta_min: 0.00000000000001
  lr: 0.001
  device: 0
